### ISSUE TITLE
Unexpected token '.' in optional?.chaining

### ISSUE THREAD

**Issue by nianxiongdi** [JuniorTour/vue-template-babel-compiler-vue-cli-project#1]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/41629087/145784591-ae6d238d-1863-4b44-a3d6-6bbb27967810.png">

**Comment by JuniorTour** [comment]
感谢你的回复！

我没能复现你的报错，刚刚在 Mac 上重新试了一遍 main 分支的 `yarn install && yarn serve`，并没有遇到你截图中的报错，一切正常。

你有做什么改动吗？执行一下 `git status` 看看结果，方便吗？
或者你的运行环境有什么特殊之处吗？是 Windows 还是 Mac 系统？

**Comment by nianxiongdi** [comment]
>

**Comment by nianxiongdi** [comment]
> 感谢你的回复！
> 
> 我没能复现你的报错，刚刚在 Mac 上重新试了一遍 main 分支的 `yarn install && yarn serve`，并没有遇到你截图中的报错，一切正常。
> 
> 你有做什么改动吗？执行一下 `git status` 看看结果，方便吗？ 或者你的运行环境有什么特殊之处吗？是 Windows 还是 Mac 系统？

@JuniorTour  我重新安装node_modules又可以了。 还有个问题咨询下，这个vue-template-babel-compiler包可以直接在webpack.config.js文件中配置嘛？

**Comment by JuniorTour** [comment]
@nianxiongdi 可以用在 webpack.config.js 中，文档中有示例：https://github.com/JuniorTour/vue-template-babel-compiler/blob/main/doc/Usage.md#2-webpack
